### ISSUE TITLE
requirements.txt está mal

### ISSUE THREAD

**Issue by jesustorresdev** [fgalvanbaez/outeazy#1]
He visto que hay una línea que da problemas:

pkg-resources==0.0.0

En principio se puede borrar:

http://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command

**Comment by fgalvanbaez** [comment]
Benas profesor,

Ok, yo me voy de viaje hasta la próxima semana, así que hasta entonces no
puedo solucionarlo. Desde que vuelva lo soluciono. Por cierto, ya te daré
algo más la lata en mayo.

Un saludo!!

**Comment by jesustorresdev** [comment]
Ok. No hay prisa. Es solo para que lo sepas.

Cuando vuelvas me explicas como se levanta el backend. Ahora solo tengo el
frontend.

Saludos.

**Comment by jesustorresdev** [comment]
Nada. Ya se como es ;)

**Comment by fgalvanbaez** [comment]
crossbar start, desde donde esta el directorio .crossbar/, desde eso ya
funciona todo!!.

Un saludo
